### ISSUE TITLE
Framework woefully out of date

### ISSUE THREAD

**Issue by powerje** [xylude/CodeIgnited#1]
Is there any reason this isn't kept up to date with https://github.com/bcit-ci/CodeIgniter? This is a travesty sir

**Comment by xylude** [comment]
Due to the massive amount of work I'm doing on other projects at this time, this project is not being supported currently.

**Comment by powerje** [comment]
I demand a Node rewrite!!

**Comment by xylude** [comment]
I'll rewrite your node, buddy. Bring it on!
